# Generated by Django 3.2.6 on 2022-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegitroVencimentoRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='...', max_length=200, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
