# Generated by Django 3.2.5 on 2021-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_has_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_pass',
            field=models.BooleanField(default=False),
        ),
    ]
