# Generated by Django 3.2.5 on 2021-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_has_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_pass',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_pass',
            field=models.BooleanField(default=False),
        ),
    ]
