# Generated by Django 3.2.5 on 2021-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210818_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_pass',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_pass',
            field=models.BooleanField(default=False),
        ),
    ]
