# Generated by Django 3.2.6 on 2022-02-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210818_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_sheets',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone'),
        ),
    ]
