# Generated by Django 3.2.6 on 2022-04-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_google_sheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_sheets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
