# Generated by Django 3.2.6 on 2022-04-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assessor')),
                ('antigo_assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antigo Assessor')),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('d0', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D0')),
                ('d1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D1')),
                ('d2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D2')),
                ('d3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D3')),
                ('d4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D4')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('troca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Troca')),
                ('rotina', models.BooleanField(default=False)),
                ('cliente_dia', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('assessor_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='NovoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_email', models.IntegerField()),
                ('categ_email_id', models.IntegerField()),
                ('data_futuro', models.DateField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_status', models.DateField(blank=True, null=True)),
                ('manual', models.CharField(blank=True, max_length=100, null=True)),
                ('data_manual', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Espelhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor_permited', models.IntegerField(verbose_name='Assessor a Espelhar')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsOnbording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assessor')),
                ('email', models.BooleanField(blank=True, default=False, null=True)),
                ('frequencia_contato', models.CharField(blank=True, choices=[('Não Definido', 'Não Definido'), ('1 mes', '1 mes'), ('3 meses', '3 meses'), ('6 meses', '6 meses'), ('12 meses', '12 meses')], max_length=12, null=True)),
                ('perfil_preenchido', models.DateTimeField(blank=True, null=True)),
                ('meio_contato', models.CharField(blank=True, choices=[('Não Definido', 'Não Definido'), ('WhatsApp', 'WhatsApp'), ('Telefone', 'Telefone'), ('Email', 'Email')], max_length=12, null=True)),
                ('acomp_permanente', models.BooleanField(blank=True, default=False, null=True)),
                ('oportunidade_rf', models.BooleanField(blank=True, default=False, null=True)),
                ('oportunidade_acoes', models.BooleanField(blank=True, default=False, null=True)),
                ('oportunidade_fii', models.BooleanField(blank=True, default=False, null=True)),
                ('oportunidade_fundos', models.BooleanField(blank=True, default=False, null=True)),
                ('sujestao', models.DateTimeField(blank=True, null=True)),
                ('alocacao', models.DateTimeField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
    ]
