# Generated by Django 3.2.6 on 2022-04-12 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assessor')),
                ('antigo_assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antigo Assessor')),
                ('data_nascimento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data de Nascimento')),
                ('d0', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D0')),
                ('d1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D1')),
                ('d2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D2')),
                ('d3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D3')),
                ('d4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D4')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('troca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Troca')),
                ('rotina', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rotina')),
                ('zap_mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zap')),
                ('cliente_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='New')),
                ('data_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Registro')),
                ('frequencia_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_acomp_per', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_acomp_rf', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_acomp_acoes', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_acomp_fii', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_acomp_fiinvest', models.CharField(blank=True, max_length=100, null=True)),
                ('onbording_obs', models.TextField(blank=True, null=True)),
                ('onbording_email', models.TextField(blank=True, null=True)),
                ('onbording_envio_sugestao', models.TextField(blank=True, null=True)),
                ('onbording_impl_envio_sugestao', models.TextField(blank=True, null=True)),
                ('onbording_perfil_preenchido', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('assessor_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='NovoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_email', models.IntegerField()),
                ('categ_email_id', models.IntegerField()),
                ('data_futuro', models.DateField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_status', models.DateField(blank=True, null=True)),
                ('manual', models.CharField(blank=True, max_length=100, null=True)),
                ('data_manual', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Espelhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor_permited', models.IntegerField(verbose_name='Assessor a Espelhar')),
                ('data', models.DateField(default=datetime.date.today)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
