# Generated by Django 3.2.6 on 2022-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=100, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('assessor', models.CharField(max_length=100, verbose_name='Assessor')),
                ('data_nascimento', models.CharField(max_length=100, verbose_name='Data de Nascimento')),
            ],
        ),
    ]
