# Generated by Django 3.2.6 on 2022-05-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='testanddo',
        ),
    ]
