# Generated by Django 3.2.6 on 2022-04-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='alldone',
            field=models.BooleanField(default=False),
        ),
    ]
