# Generated by Django 3.2.6 on 2022-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientes_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
