# Generated by Django 3.2.6 on 2022-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220317_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
