# Generated by Django 3.2.6 on 2022-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='assessor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assessor'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
