# Generated by Django 3.2.6 on 2022-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientes_alldone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
