# Generated by Django 3.2.6 on 2022-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientes_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='d0',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo em D0'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='d1',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo em D1'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='d2',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo em D2'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='d3',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo em D3'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='d4',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo em D4'),
        ),
    ]
