# Generated by Django 3.2.6 on 2022-02-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20220207_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
