# Generated by Django 3.2.6 on 2022-04-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientes_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteOnbording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Possui participação societária em alguma empresa?')),
                ('pergunta2', models.CharField(blank=True, choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica'), ('Não possui', 'Não possui')], max_length=15, null=True, verbose_name='O SEU plano de saúde é através de?')),
                ('pergunta3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantas vidas estão cobertas pelo seu plano?')),
                ('pergunta4', models.CharField(blank=True, choices=[('Não realizo', 'Não realizo'), ('Semanalmente', 'Semanalmente'), ('Quinzenalmente', 'Quinzenalmente'), ('Mensalmente', 'Mensalmente'), ('Esporadicamente', 'Esporadicamente')], max_length=15, null=True, verbose_name='O SEU plano de saúde é através de?')),
                ('pergunta5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual estratégia?')),
                ('pergunta6', models.CharField(blank=True, choices=[('Não realizo', 'Não realizo'), ('Semanalmente', 'Semanalmente'), ('Quinzenalmente', 'Quinzenalmente'), ('Mensalmente', 'Mensalmente'), ('Esporadicamente', 'Esporadicamente')], max_length=20, null=True, verbose_name='Com que frequência realiza operações de câmbio?')),
                ('pergunta7', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Possui ou está pensando em contratar crédito imobiliário?')),
                ('pergunta8', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Acompanhamento Permanente')),
                ('pergunta9', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Oportunidades de Renda Fixa')),
                ('pergunta10', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Oportunidades de Fundos de Investimentos')),
                ('pergunta11', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Oportunidades de Ações')),
                ('pergunta12', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Oportunidades de Fundos Imobiliários')),
                ('pergunta13', models.TextField(blank=True, null=True, verbose_name='Sinta-se à vontade para deixar abaixo suas críticas e sugestões. Diga-nos como podemos melhorar o nosso contato com você.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientes')),
            ],
        ),
    ]
