# Generated by Django 3.2.6 on 2022-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20220501_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='jaContactei',
            field=models.BooleanField(default=False),
        ),
    ]
