# Generated by Django 3.2.6 on 2022-02-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='d0',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D0'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D1'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D2'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D3'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D4'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Saldo em D5'),
        ),
    ]
