# Generated by Django 3.2.6 on 2022-02-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20220207_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='d5',
        ),
    ]
