# Generated by Django 3.2.6 on 2022-05-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientes_jacontactei'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='testando',
            field=models.BooleanField(default=False),
        ),
    ]
