# Generated by Django 3.2.6 on 2022-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20220412_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nome_completo',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
