# Generated by Django 3.2.6 on 2022-04-24 17:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_enqueteonbording_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteonbording',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Cliente'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta1',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Possui participação societária em alguma empresa?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Não realizo', 'Não realizo'), ('Semanalmente', 'Semanalmente'), ('Quinzenalmente', 'Quinzenalmente'), ('Mensalmente', 'Mensalmente'), ('Esporadicamente', 'Esporadicamente')], max_length=200, null=True, verbose_name='O SEU plano de saúde é através de?'),
        ),
    ]
