# Generated by Django 3.2.6 on 2022-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20220424_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta4',
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta1',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Possui participação societária em alguma empresa?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta10',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Oportunidades de Fundos de Investimentos'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta11',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Oportunidades de Ações'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta12',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Oportunidades de Fundos Imobiliários'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta2',
            field=models.CharField(choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica'), ('Não possui', 'Não possui')], default='Pessoa Física', max_length=15, verbose_name='O SEU plano de saúde é através de?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantas vidas estão cobertas pelo seu plano?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta6',
            field=models.CharField(choices=[('Não realizo', 'Não realizo'), ('Semanalmente', 'Semanalmente'), ('Quinzenalmente', 'Quinzenalmente'), ('Mensalmente', 'Mensalmente'), ('Esporadicamente', 'Esporadicamente')], default='Não realizo', max_length=20, verbose_name='Com que frequência realiza operações de câmbio?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta7',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Possui ou está pensando em contratar crédito imobiliário?'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta8',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Acompanhamento Permanente'),
        ),
        migrations.AlterField(
            model_name='enqueteonbording',
            name='pergunta9',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='Oportunidades de Renda Fixa'),
        ),
    ]
