# Generated by Django 3.2.6 on 2022-02-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='old_assessor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assessor'),
        ),
    ]
