# Generated by Django 3.2.6 on 2022-04-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20220424_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta1',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta10',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta11',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta12',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta13',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta2',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta3',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta5',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta6',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta7',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta8',
        ),
        migrations.RemoveField(
            model_name='enqueteonbording',
            name='pergunta9',
        ),
    ]
