# Generated by Django 3.2.6 on 2022-02-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientes_old_assessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='old_assessor',
            new_name='novo_assessor',
        ),
    ]
