# Generated by Django 3.2.6 on 2022-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20220218_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='rotina',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rotina'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='zap_mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zap'),
        ),
    ]
