# Generated by Django 3.2.6 on 2022-02-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20220221_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cliente_dia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='New'),
        ),
    ]
