# Generated by Django 3.2.5 on 2021-08-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(choices=[('CRA', 'CRA'), ('CRI', 'CRI'), ('LF', 'LF'), ('Debenture', 'Debenture'), ('Debenture Incentivada', 'Debenture Incentivada')], max_length=100, verbose_name='Ativo')),
                ('emissor', models.CharField(max_length=255, verbose_name='Emissor')),
                ('vol_total', models.CharField(max_length=200, verbose_name='Volume Total')),
                ('rating', models.CharField(max_length=100, verbose_name='Rating')),
                ('invet_min', models.FloatField(blank=True, null=True, verbose_name='Investimento Mínimo')),
                ('coorder', models.CharField(blank=True, max_length=255, verbose_name='Coordenadores')),
                ('garantia', models.CharField(blank=True, max_length=100, verbose_name='Garantia')),
                ('is_ir', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=100, verbose_name='Isento de IR?')),
                ('is_qualy', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100, verbose_name='Investidor Qualificado?')),
                ('is_prof', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100, verbose_name='Investidor Profissional?')),
                ('suitability', models.CharField(choices=[('A', 'Agressivo'), ('M', 'Moderado'), ('C', 'Conservador')], default='Agressivo', max_length=100, verbose_name='Suitability')),
                ('start_reserv', models.DateField(verbose_name='Início das Reservas')),
                ('end_reserv', models.DateField(verbose_name='Encerramento das Reservas')),
                ('bookbuilding', models.DateField(verbose_name='Bookbuilding')),
                ('liquid', models.DateField(verbose_name='Liquidação')),
                ('about_comp', models.TextField(blank=True, verbose_name='Sobre a Empresa')),
                ('fee', models.TextField(blank=True, verbose_name='Fee')),
                ('link_warning', models.URLField(verbose_name='Aviso ao Mercado')),
                ('link_pub', models.URLField(blank=True, verbose_name='Material de Divulgação')),
            ],
            options={
                'verbose_name': 'Renda Fixa',
                'verbose_name_plural': 'Renda Fixa',
            },
        ),
        migrations.CreateModel(
            name='OfferRvIpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Ações Ordinárias', 'Ações Ordinárias'), ('Ações Preferênciais', 'Ações Preferênciais'), ('Ações Ordinárias e Preferênciais', 'Ações Ordinárias e Preferênciais'), ('Certificados de Depósito de Ações Representativo de Ações Ordinárias Classe A', 'Certificados de Depósito de Ações Representativo de Ações Ordinárias Classe A')], max_length=200, verbose_name='Tipo de Oferta')),
                ('offer_pri', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=100, verbose_name='Oferta Primária')),
                ('offer_sec', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=100, verbose_name='Oferta Secundária')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('ticker', models.CharField(max_length=50, verbose_name='Ticker')),
                ('base_offer', models.CharField(max_length=255, verbose_name='Oferta Base')),
                ('lot_var', models.CharField(max_length=100, verbose_name='Lote Varejo')),
                ('start_fx_ind', models.FloatField(verbose_name='Fixa Indicativa Inicial')),
                ('end_fx_ind', models.FloatField(verbose_name='Fixa Indicativa Final')),
                ('start_per_res', models.DateField(verbose_name='Início do Período de Reserva')),
                ('end_per_res', models.DateField(blank=True, verbose_name='Fim do Período de Reserva')),
                ('end_vinc', models.DateField(verbose_name='Fim Vinculados')),
                ('book', models.DateField(verbose_name='Bookbuilding')),
                ('star_neg', models.DateField(verbose_name='Início das Negociações')),
                ('liquid', models.DateField(verbose_name='Liquidação')),
                ('about_comp', models.TextField(blank=True, verbose_name='Sobre a Empresa')),
                ('coorder', models.TextField(blank=True, verbose_name='Coordenadores')),
                ('dest_resor', models.TextField(blank=True, verbose_name='Destinação de Recursos')),
                ('link_pros', models.URLField(verbose_name='Prospecto')),
                ('link_warning', models.URLField(verbose_name='Aviso ao Mercado')),
                ('link_eleven', models.URLField(blank=True, verbose_name='Relatório Eleven')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPO',
            },
        ),
        migrations.CreateModel(
            name='OfferRvSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('ticker', models.CharField(max_length=50, verbose_name='Ticker')),
                ('code_subs', models.CharField(max_length=100, verbose_name='Código do Direito de Subscrição')),
                ('mkt_price', models.FloatField(verbose_name='Preço de Mercado')),
                ('mkt_price_date', models.DateField(verbose_name='Data Preço de Mercado')),
                ('ex_price', models.FloatField(verbose_name='Preço do Exercício')),
                ('dir_price', models.FloatField(verbose_name='Preço do Direito')),
                ('dir_price_date', models.DateField(verbose_name='Data Preço do Direito')),
                ('start_deal_dir', models.DateField(verbose_name='Início da Negociação do Direito')),
                ('end_deal_dir', models.DateField(verbose_name='Fim da Negociação do Direito')),
                ('start_reser', models.DateField(verbose_name='Inicio do Período de Reserva')),
                ('end_reser', models.DateField(verbose_name='Fim do Período de Reserva')),
                ('liquid', models.DateField(verbose_name='Liquidação')),
                ('fee', models.TextField(verbose_name='Fee')),
                ('fact', models.TextField(verbose_name='Fator')),
                ('date_ex', models.DateField(verbose_name='Data Ex.')),
                ('link_pdf', models.URLField(verbose_name='Link PDF')),
            ],
            options={
                'verbose_name': 'Direito de Subscrição',
                'verbose_name_plural': 'Direito de Subscrição',
            },
        ),
        migrations.CreateModel(
            name='SerieRf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Única', 'Única'), ('1ª Série', '1ª Série'), ('2ª Série', '2ª Série')], max_length=50, verbose_name='Série')),
                ('tax_top', models.CharField(max_length=100, verbose_name='Taxa Teto')),
                ('tax_ref', models.FloatField(verbose_name='Taxa Referêncial')),
                ('venciment', models.DateField(verbose_name='Vencimento')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration (em anos)')),
                ('amort', models.CharField(max_length=100, verbose_name='Amortização')),
                ('amort_beg', models.DateField(verbose_name='Início da Amortização')),
                ('jurus', models.CharField(max_length=100, verbose_name='Jurus')),
                ('current_tax', models.CharField(max_length=100, verbose_name='Taxa Atual Aproximada')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offerrf')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='ModalidadeIpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Modalidade')),
                ('fee', models.FloatField(verbose_name='Fee')),
                ('garant', models.FloatField(verbose_name='Gaantia Exigida')),
                ('min_reserv', models.FloatField(verbose_name='Reserva Mínima')),
                ('max_reserv', models.FloatField(verbose_name='Reserva Máxima')),
                ('lock_end', models.DateField(blank=True, null=True, verbose_name='Término do Lock-Up')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('modalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offerrvipo')),
            ],
        ),
        migrations.CreateModel(
            name='EmailIpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sender', models.IntegerField(blank=True, null=True)),
                ('nome_oferta', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=100)),
                ('codigo_cliente', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('modalidaade', models.CharField(max_length=100)),
                ('assessor_responsavel', models.CharField(max_length=100)),
                ('vinculo', models.CharField(max_length=10)),
                ('valFim', models.CharField(max_length=100)),
                ('preMax', models.CharField(max_length=100)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('data_sent', models.DateTimeField(auto_now_add=True)),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offerrvipo')),
            ],
        ),
    ]
