# Generated by Django 3.2.5 on 2021-08-11 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailipo',
            name='data_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
