# Generated by Django 3.2.5 on 2021-08-11 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_emailipo_data_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailipo',
            name='data_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
