# Generated by Django 3.2.5 on 2021-08-11 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_emailipo_data_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sender', models.IntegerField(blank=True, null=True)),
                ('nome_oferta', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=100)),
                ('codigo_cliente', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('assessor_responsavel', models.CharField(max_length=100)),
                ('taxa', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('data_sent', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offerrf')),
            ],
        ),
    ]
