# Generated by Django 3.2.5 on 2021-08-18 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_emailrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('emissao', models.CharField(max_length=100)),
                ('id_sender', models.IntegerField(blank=True, null=True)),
                ('nome_oferta', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=100)),
                ('codigo_cliente', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('assessor_responsavel', models.CharField(max_length=100)),
                ('valor_da_cota', models.CharField(max_length=200)),
                ('valor_financeiro', models.CharField(max_length=200)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=200)),
                ('data_sent', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
