# Generated by Django 3.2.6 on 2021-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_emailfii'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiiEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oferta', models.CharField(max_length=100, verbose_name='Id da Oferta')),
                ('data_base', models.DateField(verbose_name='Data-base')),
                ('inicio_periodo_de_negociacao', models.DateField(verbose_name='Início do Período de Negociação')),
                ('fim_periodo_de_negociacao', models.DateField(verbose_name='Fim do Período de Negociação')),
                ('inicio_periodo_preferencia', models.DateField(verbose_name='Início do Período de Preferência')),
                ('fim_periodo_preferencia', models.DateField(verbose_name='Fim do Período de Preferência')),
                ('liquidacao_periodo_preferencia', models.DateField(verbose_name='Liquidação do Período de Preferência')),
                ('inicio_periodo_sobra', models.DateField(verbose_name='Início do Período de Sobra')),
                ('fim_periodo_sobra', models.DateField(verbose_name='Fim do Período de Sobra')),
                ('liquidacao_periodo_sobra', models.DateField(verbose_name='Liquidação do Período de Sobra')),
                ('inicio_periodo_publico', models.DateField(verbose_name='Início do Período Público')),
                ('fim_periodo_publico', models.DateField(verbose_name='Fim do Período Público')),
                ('liquidacao_periodo_publico', models.DateField(verbose_name='Liquidação do Período Público')),
            ],
        ),
    ]
