# Generated by Django 3.2.6 on 2021-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_fiiedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiiedit',
            name='modalidade_adicional',
            field=models.CharField(default='...', max_length=255, verbose_name='Modalidade Adicional'),
        ),
    ]
