# Generated by Django 3.2.6 on 2021-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_fiiedit_modalidade_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiiedit',
            name='fim_periodo_de_negociacao',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período de Negociação'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='fim_periodo_preferencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período de Preferência'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='fim_periodo_publico',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período Público'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='fim_periodo_sobra',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período de Sobra'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='inicio_periodo_de_negociacao',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período de Negociação'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='inicio_periodo_preferencia',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período de Preferência'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='inicio_periodo_publico',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período Público'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='inicio_periodo_sobra',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período de Sobra'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='liquidacao_periodo_preferencia',
            field=models.DateField(blank=True, null=True, verbose_name='Liquidação do Período de Preferência'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='liquidacao_periodo_publico',
            field=models.DateField(blank=True, null=True, verbose_name='Liquidação do Período Público'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='liquidacao_periodo_sobra',
            field=models.DateField(blank=True, null=True, verbose_name='Liquidação do Período de Sobra'),
        ),
        migrations.AlterField(
            model_name='fiiedit',
            name='modalidade_adicional',
            field=models.CharField(blank=True, default='...', max_length=255, null=True, verbose_name='Modalidade Adicional'),
        ),
    ]
