# Generated by Django 3.2.6 on 2021-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20211130_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiiedit',
            name='data_base',
            field=models.DateField(blank=True, null=True, verbose_name='Data-base'),
        ),
    ]
