# Generated by Django 3.2.6 on 2022-03-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_fiiedit_data_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrvsubscription',
            name='mkt_price_time',
            field=models.TimeField(null=True, verbose_name='Hora Preço de Mercado'),
        ),
        migrations.AlterField(
            model_name='offerrvsubscription',
            name='mkt_price_date',
            field=models.DateTimeField(verbose_name='Data Preço de Mercado'),
        ),
    ]
