# Generated by Django 3.2.6 on 2022-04-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20220331_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfii',
            name='emissao',
        ),
    ]
