# Generated by Django 3.2.6 on 2022-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_remove_emailfii_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisttoEmailFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.IntegerField(blank=True, max_length=10, null=True)),
                ('enviado_por', models.IntegerField(blank=True, max_length=10, null=True)),
                ('remetente', models.IntegerField(blank=True, max_length=10, null=True)),
                ('preco_mercado', models.FloatField(blank=True, max_length=100, null=True)),
                ('data_prec_mercado', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('preco_oferta', models.FloatField(blank=True, max_length=100, null=True)),
                ('quantidade', models.IntegerField(blank=True, max_length=100, null=True)),
                ('conteudo_email', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailFii',
        ),
    ]
