# Generated by Django 3.2.6 on 2022-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20220422_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registtoemailfii',
            name='cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registtoemailfii',
            name='enviado_por',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registtoemailfii',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registtoemailfii',
            name='remetente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
