# Generated by Django 3.2.6 on 2022-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20220422_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='registtoemailfii',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
