# Generated by Django 3.2.6 on 2022-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcategoria',
            name='criado_por',
            field=models.IntegerField(blank=True, null=True, verbose_name='Criado por:'),
        ),
        migrations.AlterField(
            model_name='emailcategoria',
            name='data_insert',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='emailcategoria',
            name='editado_por',
            field=models.IntegerField(blank=True, null=True, verbose_name='Editado por:'),
        ),
    ]
