# Generated by Django 3.2.6 on 2022-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220301_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcategoria',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='emailcategoria',
            name='cabecalho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cabeçalho'),
        ),
        migrations.AddField(
            model_name='emailcategoria',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo'),
        ),
    ]
